/**
 * Permission codes, mirroring the backend seed. The UI gates purely on these — the authoritative
 * set for the logged-in user comes from GET /auth/me (never from the JWT, which carries only roleId).
 */
export const PERMISSIONS = {
  ORG_COMPANY_READ: "ORG_COMPANY_READ",
  ORG_COMPANY_WRITE: "ORG_COMPANY_WRITE",
  ORG_REGION_READ: "ORG_REGION_READ",
  ORG_REGION_WRITE: "ORG_REGION_WRITE",
  ORG_BRANCH_READ: "ORG_BRANCH_READ",
  ORG_BRANCH_WRITE: "ORG_BRANCH_WRITE",
  ORG_DEPARTMENT_READ: "ORG_DEPARTMENT_READ",
  ORG_DEPARTMENT_WRITE: "ORG_DEPARTMENT_WRITE",
  ORG_DESIGNATION_READ: "ORG_DESIGNATION_READ",
  ORG_DESIGNATION_WRITE: "ORG_DESIGNATION_WRITE",
  CUSTOMER_READ: "CUSTOMER_READ",
  CUSTOMER_WRITE: "CUSTOMER_WRITE",
  PRODUCT_READ: "PRODUCT_READ",
  PRODUCT_WRITE: "PRODUCT_WRITE",
  POLICY_READ: "POLICY_READ",
  POLICY_WRITE: "POLICY_WRITE",
  CLAIM_READ: "CLAIM_READ",
  CLAIM_WRITE: "CLAIM_WRITE",
  CLAIM_SUBMIT: "CLAIM_SUBMIT",
  CLAIM_ASSIGN: "CLAIM_ASSIGN",
  CLAIM_DECIDE: "CLAIM_DECIDE",
  CLAIM_INVESTIGATE: "CLAIM_INVESTIGATE",
  FRAUD_READ: "FRAUD_READ",
  RULESET_READ: "RULESET_READ",
  RULESET_WRITE: "RULESET_WRITE",
  AUDIT_READ: "AUDIT_READ",
  ANALYTICS_READ: "ANALYTICS_READ",
  USER_READ: "USER_READ",
  USER_WRITE: "USER_WRITE",
  COVERAGE_READ: "COVERAGE_READ",
  COVERAGE_WRITE: "COVERAGE_WRITE",
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
  PORTAL_CLAIM_READ: "PORTAL_CLAIM_READ",
  PORTAL_CLAIM_WRITE: "PORTAL_CLAIM_WRITE",
  PORTAL_POLICY_READ: "PORTAL_POLICY_READ",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
